### ISSUE TITLE
srsRAN MATALB Assertion Failed while testing

### ISSUE THREAD

**Issue by golisrikanth1989** [srsran/srsRAN_matlab#3]
Hi Team,

I wanted check this matlab based srsRAN test and following the doc below, https://docs.srsran.com/projects/project/en/latest/tutorials/source/matlab/source/index.html#installation

Using the MATLAB 2023b version. While running and test the scripts, One test getting failed and its error message is shown in below,

I was getting this issue from the ans variable in (1,1) location. I am not sure which file to change can anyone help to resolve this issue.

assertEqual failed.--> Classes do not match.        Actual Class:        logical    Expected Class:        doubleActual Value:  logical   0Expected Value:     0
__________

Failure Summary:

     Name                             Failed  Incomplete  Reason(s)
    ===========================================================================
     CheckAnalyzers/checkParserPUSCH    X         X       Failed by assertion.

ans = 

  1×94 TestResult array with properties:

    Name
    Passed
    Failed
    Incomplete
    Duration
    Details

Totals:
   93 Passed, 1 Failed (rerun), 1 Incomplete.
   21.7829 seconds testing time.
   
   Thanks,
   Srikanth

**Comment by dvdgrgrtt** [comment]
Hi @golisrikanth1989,
thanks for pointing this out. We haven't tested our software with R2023b, only with R2023a (and some previous versions). However, we've encountered a similar error before when going from R2022b to R2023a. The reason is that MATLAB has probably changed the default type of one of the fields inside an NR object.
Can you rerun the failed test and paste the entire output? I can't see exactly which assertion is failing - my guess is
```matlab
            obj.assertEqual(pusch.TransformPrecoding, 0, 'Wrong transform precoding.');
```
on line 133 of `unitTests/CheckAnalyzers.m`. If so, just change it to
```matlab
            obj.assertEqual(double(pusch.TransformPrecoding), 0, 'Wrong transform precoding.');
```
and it should work. We'll fix this in the next release.

**Comment by golisrikanth1989** [comment]
Hi @dvdgrgrtt,

Thanks for the response,

Now its getting passed with all test, here is the output,

.
Done CheckAnalyzers
__________

Running CheckSimulators

Simulating transmission scheme 1 (1x1) and SCS=15kHz with AWGN channel at -5.6dB SNR for 100 10ms frame(s)

Throughput(Mbps) after 10 frame(s) = 0.0000 (max 1.8000)
Throughput(%) after 10 frame(s) = 0.0000
BLER after 10 frame(s) = 1.0000

Simulating transmission scheme 1 (1x1) and SCS=15kHz with AWGN channel at -5.4dB SNR for 100 10ms frame(s)

Throughput(Mbps) after 10 frame(s) = 0.0000 (max 1.8000)
Throughput(%) after 10 frame(s) = 0.0000
BLER after 10 frame(s) = 1.0000

Simulating transmission scheme 1 (1x1) and SCS=15kHz with AWGN channel at -5.2dB SNR for 100 10ms frame(s)

Throughput(Mbps) after 10 frame(s) = 0.0178 (max 1.8000)
Throughput(%) after 10 frame(s) = 0.9901
BLER after 10 frame(s) = 0.9901

Simulating transmission scheme 1 (1x1) and SCS=15kHz with AWGN channel at -5dB SNR for 100 10ms frame(s)

Throughput(Mbps) after 11 frame(s) = 0.1636 (max 1.8000)
Throughput(%) after 11 frame(s) = 9.0909
BLER after 11 frame(s) = 0.9091

Simulating transmission scheme 1 (1x1) and SCS=15kHz with AWGN channel at -4.8dB SNR for 100 10ms frame(s)

Throughput(Mbps) after 15 frame(s) = 0.5755 (max 1.8000)
Throughput(%) after 15 frame(s) = 31.9728
BLER after 15 frame(s) = 0.6803
.11:38:25: Simulating SNR = -14.2 dB... Detection probability (ignoring time error):        100.00%
                                       Detection probability (time error below tolerance): 100.00%
                                       Time error:                                         0.21 +/- 0.25
11:38:26: Simulating SNR = -14.2 dB... False-alarm probability: 0.00%
.
Done CheckSimulators
__________

Running CheckTests
.......... .......... .......... .......... ....Running srsChEqualizerUnittest
.
Done srsChEqualizerUnittest
__________

.Running srsChEstimatorUnittest
.
Done srsChEstimatorUnittest
__________

.Running srsDFTProcessorUnittest
.
Done srsDFTProcessorUnittest
__________

.Running srsDemodulationMapperUnittest
.
Done srsDemodulationMapperUnittest
__________

.Running srsLDPCEncoderUnittest
.
Done srsLDPCEncoderUnittest
__________

.Running srsLDPCRateMatcherUnittest
.
Done srsLDPCRateMatcherUnittest
__________

.
Running srsLDPCSegmenterUnittest
.
Done srsLDPCSegmenterUnittest
__________

.Running srsModulationMapperUnittest
.
Done srsModulationMapperUnittest
__________

.Running srsNZPCSIRSGeneratorUnittest
.
Done srsNZPCSIRSGeneratorUnittest
__________

.Running srsOFDMDemodulatorUnittest
.
Done srsOFDMDemodulatorUnittest
__________

.Running srsOFDMModulatorUnittest
.
Done srsOFDMModulatorUnittest
__________

.Running srsOFHCompressionUnittest
.
Done srsOFHCompressionUnittest
__________

.Running srsPBCHEncoderUnittest
.
Done srsPBCHEncoderUnittest
__________

.Running srsPBCHModulatorUnittest
.
Done srsPBCHModulatorUnittest
__________

.Running srsPBCHdmrsUnittest
.
Done srsPBCHdmrsUnittest
__________

.Running srsPDCCHCandidatesCommonUnittest
.
Done srsPDCCHCandidatesCommonUnittest
__________

. Running srsPDCCHCandidatesUeUnittest
.
Done srsPDCCHCandidatesUeUnittest
__________

.Running srsPDCCHEncoderUnittest
.
Done srsPDCCHEncoderUnittest
__________

.Running srsPDCCHModulatorUnittest
.
Done srsPDCCHModulatorUnittest
__________

.Running srsPDCCHProcessorUnittest
.
Done srsPDCCHProcessorUnittest
__________

.Running srsPDCCHdmrsUnittest
.
Done srsPDCCHdmrsUnittest
__________

.Running srsPDSCHEncoderUnittest
.
Done srsPDSCHEncoderUnittest
__________

.Running srsPDSCHModulatorUnittest
.
Done srsPDSCHModulatorUnittest
__________

.Running srsPDSCHProcessorUnittest
.
Done srsPDSCHProcessorUnittest
__________

.Running srsPDSCHdmrsUnittest
.
Done srsPDSCHdmrsUnittest
__________

.Running srsPRACHDemodulatorUnittest
.
Done srsPRACHDemodulatorUnittest
__________

. Running srsPRACHDetectorUnittest
.
Done srsPRACHDetectorUnittest
__________

.Running srsPRACHGeneratorUnittest
.
Done srsPRACHGeneratorUnittest
__________

.Running srsPUCCHDemodulatorFormat2Unittest
.
Done srsPUCCHDemodulatorFormat2Unittest
__________

.Running srsPUCCHDetectorFormat1Unittest
.
Done srsPUCCHDetectorFormat1Unittest
__________

.Running srsPUCCHProcessorFormat1Unittest
.
Done srsPUCCHProcessorFormat1Unittest
__________

.Running srsPUCCHProcessorFormat2Unittest
.
Done srsPUCCHProcessorFormat2Unittest
__________

.Running srsPUCCHdmrsUnittest
.
Done srsPUCCHdmrsUnittest
__________

.Running srsPUSCHDecoderUnittest
.
Done srsPUSCHDecoderUnittest
__________

.Running srsPUSCHDemodulatorUnittest
.
Done srsPUSCHDemodulatorUnittest
__________

.Running srsPUSCHProcessorUnittest
.
Done srsPUSCHProcessorUnittest
__________

. Running srsPUSCHdmrsUnittest
.
Done srsPUSCHdmrsUnittest
__________

.Running srsSSBProcessorUnittest
.
Done srsSSBProcessorUnittest
__________

.Running srsShortBlockDetectorUnittest
.
Done srsShortBlockDetectorUnittest
__________

.Running srsShortBlockEncoderUnittest
.
Done srsShortBlockEncoderUnittest
__________

.Running srsTBSCalculatorUnittest
.
Done srsTBSCalculatorUnittest
__________

.Running srsUCIDecoderUnittest
.
Done srsUCIDecoderUnittest
__________

.Running srsULSCHDemultiplexUnittest
.
Done srsULSCHDemultiplexUnittest
__________

.Running srsULSCHInfoUnittest
.
Done srsULSCHInfoUnittest
__________

..
Done CheckTests
__________


ans = 

  1×94 TestResult array with properties:

    Name
    Passed
    Failed
    Incomplete
    Duration
    Details

Totals:
   94 Passed, 0 Failed, 0 Incomplete.
   25.0424 seconds testing time.

I will check the analyzers and simulators let you know, If found any issues.


Thanks
------------
Srikanth Goli

**Comment by dvdgrgrtt** [comment]
Closing this issue - feel free to reopen if needed.
